#### general settings
name: OCTData1
model_type: OCTDegSRModel
scale: 4
num_gpu: 2  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0


#### datasets
datasets:
  train:
    name: OCTX4
    type: UnpairedOCTDataset
    io_backend:
      type: lmdb
    color: Gray
    ratios: [10, 10]

    dataroot_gt: /home/data/OCT_data/Unpaired_dataset/resol_3d8_10.lmdb
    dataroot_lq: /home/data/OCT_data/Unpaired_dataset/resol_16_40.lmdb

    
    gt_size: 128
    # lq_size: 32
    use_hflip: True
    use_rot: False

    # data loader
    num_worker_per_gpu: 12
    batch_size_per_gpu: 24
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: OCT16_40_val
    type: SingleImageDataset
    io_backend:
      type: lmdb
    color: Gray
    dataroot_lq: /home/data/OCT_data/Unpaired_dataset/resol_16_40.lmdb

#### network structures
networks:
  network_deg:
    type: OCTDegModel
    scale: 4
    num_in_ch: 1
    kernel_opt:
      spatial: true
      mix: false
      nc: 1
      nf: 64
      nb: 8
      head_k: 1
      body_k: 1
      ksize: 11
      zero_init: true
    noise_opt: 
      spatial: true
      mix: false
      nc: 1
      nf: 32
      nb: 8
      head_k: 3
      body_k: 3
      dim: 1
      zero_init: true
  
  network_dis1:
    type: PatchGANDiscriminator
    num_in_ch: 1
    num_feat: 64
    num_b: 3
    stride: 1


  network_dis2:
    type: PatchGANDiscriminator
    num_in_ch: 1
    num_feat: 64
    num_b: 3
    stride: 1

network_g:
  type: EDSR
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 256
  num_block: 32
  upscale: 4
  res_scale: 1
  img_range: 255.
  # rgb_mean: [0.4488, 0.4371, 0.4040]

# path
path:
  # use the pre-trained Real-ESRNet model
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~
      
#### training settings: learning rate scheme, loss
train:
  ema_decay: 0.999
  resume_state: ~
  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0

  optim_deg: true
  optim_sr: true

  scheduler:
    type: MultiStepRestartLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5
  
  losses:
    noise_mean:
      type: MSELoss
      loss_weight: 1.0
    
    sr_pixel:
      type: L1Loss
      loss_weight: !!float 1.0
      reduction: mean
    
    sr_perceptual:
      type: PerceptualLoss
      layer_weights:
        'conv5_4': 1  # before relu
      vgg_type: vgg19
      use_input_norm: true
      range_norm: false
      perceptual_weight: 1.0
      style_weight: 0
      criterion: l1
      # loss_weight: !!float 5e-2
    
    lr_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      loss_weight: !!float 5e-2
    
    sr_adv:
      type: GANLoss
      gan_type: vanilla
      real_label_val: 1.0
      fake_label_val: 0.0
      loss_weight: !!float 5e-2
    

  optimizers:
    default:
      type: Adam
      lr: !!float 2e-4
    network_deg: ~
    net_g: ~
    network_dis1: ~
    network_dis2: ~

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # scheduler:
  #   type: MultiStepRestartLR
  #   milestones: [50000, 100000, 200000, 300000]
  #   gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 2
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
# dist training settings
dist_params:
  backend: nccl
  port: 29500


